Insert into exchange_value(currency_from,currency_to,conversion_multiple,port) values('USD','INR',65,0)
Insert into exchange_value(currency_from,currency_to,conversion_multiple,port) values('EUR','INR',75,0)
Insert into exchange_value(currency_from,currency_to,conversion_multiple,port) values('AUD','INR',25,0)
Insert into exchange_value(currency_from,currency_to,conversion_multiple,port) values('CAD','INR',50,0)
Insert into exchange_value(currency_from,currency_to,conversion_multiple,port) values('SGD','INR',56,0)
Insert into exchange_value(currency_from,currency_to,conversion_multiple,port) values('MYR','INR',46,0)